site_name: Architype learn
copyright: |
  &copy; Architype Ltd, 2020

theme: 
  name: material
  favicon: img/favicon.ico
  logo: material/library/logo.png
  palette:
    scheme: preference
    primary: black
    accent: deep orange
  font: 
    text: Roboto
  features:
    - navigation.instants

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 6
      
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://architypeukcomms.slack.com/archives/CVC8CUQTX

plugins:
  - search:
      prebuild_index: true

# Page tree    
nav:
  - Home: index.md
  - Revit Standards:
    - Introduction: revit-standards/introduction-main.md
    - Project Setup: revit-standards/project-setup.md
    - Folder Structure *: revit-standards/folder-structure.md
    - File Naming *: revit-standards/file-naming.md
    - Sheet Naming *: revit-standards/sheet-naming.md
    - View Naming *: revit-standards/view-naming.md
    - Component Naming *: revit-standards/component-naming.md
    - Annotation *: revit-standards/annotation.md
    - Groups *: revit-standards/groups.md
    - Desktop Shortcuts *: revit-standards/desktop-shortcuts.md 
  - Revit PHPP Plugins:
    - Introduction: revit-phpp-plugins/introduction-phpp-plugins.md
    - PHPP Window Family: revit-phpp-plugins/window-family.md
  - Navisworks: 
    - Introduction: navisworks/introduction-navisworks.md
  - BIMCollab: 
    - Introduction: bimcollab/introduction-bimcollab.md
  - About: about/about-this-site.md
    